/**
 * Vault-health report (#156) — the curator's human review surface, projected
 * as Markdown INTO the vault (Obsidian is the viewer; same direction as the
 * #140 audit projection). The report proposes, a human decides: nothing in
 * here deletes or moves anything.
 *
 * Pure renderer + a small atomic writer. Data collection (joining usage,
 * curator state, floors, vault index) lives with the caller — this module
 * has no I/O dependencies beyond writing the file.
 */
import { readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { StaleEntry } from "./curator.js";
import type { UsageEntry } from "./usage-sidecar.js";

export const REPORT_FILENAME = "REPORT.md";

export interface ReportStaleCandidate {
  id: string;
  title?: string;
  usage?: UsageEntry;
  entry: StaleEntry;
}

/** Would-be candidate whose observation window has not matured yet. */
export interface ReportPendingCandidate {
  id: string;
  title?: string;
  usage?: UsageEntry;
  reason: string;
}

export interface ReportFloorEntry {
  memory_id: string;
  title?: string;
  reason: string;
  floored_at: string;
  last_affirmed: string;
  affirmed_by?: string;
  why?: string;
  /** Weeks since last_affirmed, precomputed by the caller. */
  weeksSinceAffirm: number;
  /** True when the floor was never affirmed after its initial add. */
  neverReaffirmed: boolean;
}

export interface ReportConflictCluster {
  topicPath: string[];
  memberIds: string[];
}

export interface ReportDanglingLink {
  fromId: string;
  target: string;
}

export interface VaultHealthData {
  generatedAt: string;
  vaultSize: number;
  stale: ReportStaleCandidate[];
  /** Candidates gated only by the immature observation window. */
  pending?: ReportPendingCandidate[];
  floors: ReportFloorEntry[];
  conflicts: ReportConflictCluster[];
  dangling: ReportDanglingLink[];
  /** Vault-relative paths of 0-byte .md files — usually Obsidian's
   *  auto-created empty notes from clicking an unresolved wikilink. */
  emptyFiles?: string[];
  /** True on review-only passes (dry-run / first-ever run): the stale list
   *  shows what WOULD be demoted — nothing has acted yet. */
  pendingReview?: boolean;
}

function fmtUsage(u?: UsageEntry): string {
  if (!u) return "no recorded usage";
  const last = u.last_acted_on_at ?? u.last_loaded_at ?? "never";
  return `surfaced ${u.surfaced}× · loaded ${u.loaded}× · acted_on ${u.acted_on}× · last engagement: ${last}`;
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

/**
 * Render the full report. Deterministic for identical data (the only
 * timestamp is data.generatedAt), heading/anchor structure stable across
 * runs so re-runs update in place.
 */
export function renderVaultHealthReport(data: VaultHealthData): string {
  const L: string[] = [];
  L.push("<!-- bastra-report:start — generated by the bastra curator; edits here are overwritten on the next run -->");
  L.push("# Vault Health");
  L.push("");
  L.push(`Generated ${data.generatedAt} · ${data.vaultSize} active memories · this report **proposes** — you decide. Nothing was deleted or moved.`);
  L.push("");

  L.push("<!-- bastra-report:stale -->");
  L.push("## Stale candidates (score-only demotions)");
  L.push("");
  if (data.stale.length === 0) {
    L.push("None. No memory is currently demoted for staleness.");
  } else {
    L.push(
      data.pendingReview
        ? "These keep being surfaced without ever earning engagement — this was a **review pass**: nothing is demoted yet. The next scheduled pass will demote them (score-only: `load_memory` and every citation still resolve) unless they earn engagement first."
        : "These keep being surfaced without ever earning engagement — they now rank lower (demotion is score-only: `load_memory` and every citation still resolve). A real load or acted-on use reactivates them automatically. To retire one for good, delete or archive it yourself.",
    );
    L.push("");
    for (const s of data.stale) {
      L.push(`- [[${s.id}]]${s.title ? ` — ${s.title}` : ""}`);
      L.push(`  - ${fmtUsage(s.usage)}`);
      L.push(`  - stale since ${fmtDate(s.entry.stale_since)}: ${s.entry.reason}`);
    }
  }
  if (data.pending && data.pending.length > 0) {
    L.push("");
    L.push("**Watching** (usage window still maturing — nothing will be demoted before a full engagement window of data exists):");
    L.push("");
    for (const p of data.pending) {
      L.push(`- [[${p.id}]]${p.title ? ` — ${p.title}` : ""} · ${fmtUsage(p.usage)}`);
    }
  }
  L.push("");

  L.push("<!-- bastra-report:floors -->");
  L.push("## Floors awaiting re-affirmation");
  L.push("");
  if (data.floors.length === 0) {
    L.push("None. Every active floor was recently affirmed.");
  } else {
    L.push("These entries spend *guaranteed* context on every session. The engine never expires a floor — review whether each still earns its place: re-affirm it (with a fresh why) or release it. An expired floor drops back to ranked; it is never deleted.");
    L.push("");
    for (const f of data.floors) {
      const affirm = f.neverReaffirmed
        ? `floored ${fmtDate(f.floored_at)}, **never re-affirmed** (${f.weeksSinceAffirm} weeks)`
        : `last affirmed ${fmtDate(f.last_affirmed)} (${f.weeksSinceAffirm} weeks ago)${f.affirmed_by ? ` by ${f.affirmed_by}` : ""}`;
      L.push(`- [[${f.memory_id}]]${f.title ? ` — ${f.title}` : ""}`);
      L.push(`  - reason: ${f.reason}`);
      L.push(`  - ${affirm}${f.why ? ` — why: ${f.why}` : ""}`);
    }
  }
  L.push("");

  L.push("<!-- bastra-report:conflicts -->");
  L.push("## Same-topic clusters (conflict review candidates)");
  L.push("");
  if (data.conflicts.length === 0) {
    L.push("None. No topic path holds more than one active memory.");
  } else {
    L.push("Multiple active memories share the exact same topic path — worth a look for contradictions, near-duplicates, or a merge. (Deterministic pass: this lists co-location, it does not judge content.)");
    L.push("");
    for (const c of data.conflicts) {
      L.push(`- \`${c.topicPath.join(" / ")}\`: ${c.memberIds.map((id) => `[[${id}]]`).join(" · ")}`);
    }
  }
  L.push("");

  L.push("<!-- bastra-report:dangling -->");
  L.push("## Dangling wikilinks");
  L.push("");
  if (data.dangling.length === 0) {
    L.push("None. Every `[[wikilink]]` resolves to an active memory.");
  } else {
    L.push("Links pointing at ids that no longer exist in the active vault (renamed, trashed, or never created). Fix the link or create the memory it promises.");
    L.push("");
    for (const d of data.dangling) {
      L.push(`- [[${d.fromId}]] → \`[[${d.target}]]\` (missing)`);
    }
  }
  L.push("");
  L.push("<!-- bastra-report:empty-files -->");
  L.push("## Empty files");
  L.push("");
  if (!data.emptyFiles || data.emptyFiles.length === 0) {
    L.push("None. No 0-byte `.md` files in the vault.");
  } else {
    L.push("Zero-byte markdown files — typically created by Obsidian when a wikilink that does not resolve to a file (e.g. a bastra doc-id link) gets clicked. They carry nothing and are safe to delete.");
    L.push("");
    for (const p of data.emptyFiles) {
      L.push(`- \`${p}\``);
    }
  }
  L.push("");
  L.push("<!-- bastra-report:end -->");
  L.push("");
  return L.join("\n");
}

/**
 * Atomic write of the report into the vault root. Never throws. Refuses to
 * clobber a pre-existing REPORT.md that is NOT ours (no bastra-report anchor
 * — e.g. a user-authored file of the same name; review find 2026-07-03).
 */
export async function writeVaultHealthReport(vaultRoot: string, data: VaultHealthData): Promise<boolean> {
  try {
    const target = join(vaultRoot, REPORT_FILENAME);
    try {
      const existing = await readFile(target, "utf8");
      if (!existing.includes("<!-- bastra-report:start")) return false;
    } catch {
      /* no existing file — free to create */
    }
    const tmp = `${target}.tmp-${process.pid}`;
    await writeFile(tmp, renderVaultHealthReport(data), "utf8");
    await rename(tmp, target);
    return true;
  } catch {
    return false;
  }
}
